### ISSUE TITLE
Distance inconsistent

### ISSUE THREAD

**Issue by craigsned** [IZ7BOJ/direwolf_webstat#1]
Webstat config location set with the same co-ordinates as my digipeater - sometimes the last distance on summary.php is correctly reported as 0, sometimes N/A (understand that this is due to the last packet not having a location and is expected behaviour) and sometimes some seemingly random distance - e.g. 21, 28, 36, 51 Km - when all the packets have been digipeated back to me by another digi (the same digi each time) which is also static.

**Comment by IZ7BOJ** [comment]
Hi,
I'm trying to replicate the problem but I can't.
If I manually insert a raw in the log file with a dummy station reporting the same coordinates of config.php, I always see "0Km".
Can you provide access to the dashboard, so I can see it directly?
Thanks
Alfredo

**Comment by craigsned** [comment]
Hi Alfredo,

 

You should be able to get it from;

 

86.143.157.137/aprs/summary.php

 

My station is MB7UEL. 

 

There is only one other digipeater MB7VN who is just in range, so he doesn’t always rx my packet to digipeat.  You may have to choose show stations all to see MB7UEL in the list.

 

My config.php file has the location set as;

 

Lat = 56.055167

Lon= -2.709333

 

You’ll see in the frames rx that this is the same as MB7UEL is sending.

 

I’ve attached a screenshot showing that MB7UEL is currently indicated as 29.8 Km away…

 

 

Many thanks!

Craig

MM0NBW

**Comment by IZ7BOJ** [comment]
I did some investigations.
The position is calculated considering last packet received.
MB7UEL is sending two different types of packets, with different dti (data type identifier): packets "!" (position without timestamp) and "/" (position with timestamp).
In this second case, if you see the direwolf log, latitude and longitude fields are empty, then when the last packet received is "/" type, the dashboard cannot calculate the distance.
I think it's a strange behaviour of direwolf. I'll ask on the direwolf mailing list the reason.

I see also some frames with "error" columns at "1", and sometimes the latitude or the longitude are missing due to deconding error. 
In these cases, direwolf is not responsible but if the last received packet is corrupted, the distance will be N/A too.

I'll let you know. In the meantime, I leave the issue in open state.

73's
Alfredo

**Comment by IZ7BOJ** [comment]
Just last request: can you see raw packet data coming from MB7UEL with dti "/"? 
The log doesn't show raw packet data, you shoud see on your display (standard output).
Do the packets contain latitude and longitude?
Thanks,
Alfredo

**Comment by craigsned** [comment]
Hi Alfredo,
That last packet with dti "/" is a status message and has no latitude/longitude information in the packet.  This is correct behaviour.  The previous packet with dti "/#" was being reported as 29.8 Km away.

Will have to wait for the MB7VN to digipeat another "/#" packet to see what happens.

The error and no lat/long information I understand.  MB7VN is on the fringe of my RX and so not a great signal to me.  I understand that will result in an N/A message.  But there have been packets correctly RX with correct lat/long still with strange distances.

**Comment by IZ7BOJ** [comment]
You’re right, I see only / and /# packets.
Let me know when you get new packet
Alfredo

Il giorno ven 7 gen 2022 alle 11:44 craigsned ***@***.***> ha
scritto:

**Comment by craigsned** [comment]
OK, there is a new packet just in, and it is showing correctly as 0 Km...!!!

I just noticed that the last packet which was showing as 29.8 Km had an error, but is logged as the correct lat/long.  Interesting.  Could be an error introduced at a lower level before translation to text?  If so I guess I'll just have to accept :-)

**Comment by craigsned** [comment]
Im noticing changes in distance for other static stations where there are errors/no errors.  I've not managed to keep a log to track these, just what I noticed while doing other work.   Seems we are zeroing in on the "issue" being something to do with the packet errors, even though the displayed/logged lat/long is consistently correct.

I'm keeping a log of distances/bearings/packet error - will let you have my observations later.

**Comment by craigsned** [comment]
Hi Alfredo,

I think I have tracked it down!  My digipeater is sending out object packets as well for two local repeaters.  These have different lat/long and are being picked up as location for MB7UEL, rather than the object callsign.

**Comment by craigsned** [comment]
As above, I think I have figured out what is happening, but this is now throwing up another potential issue;

The summary page shows last rx packet for MB7UEL at 12:00:20 (with incorrect location).  Cross checking with aprs.fi raw packets I see that this corresponds to the object TX for GB3LB.  However, going to show frames, the last frame reported for MB7UEL is at 10:45:35.   I notice that within the frames RX there are none for the two objects GB3FF/GB3LB which suggests that these are being parsed by webstat differently.  Neither GB3FF or GB3LB appear on the stations heard...  I have confirmed they are in the Direwolf log.

**Comment by IZ7BOJ** [comment]
Hi Craig,
you're right, the table on summary page shows "source" field, not "name".
I've just modified functions.php in order to consider "name", you can try now
I've checked that frames.php page was correct, because considered "name" field.
Let me know.
Alfredo

**Comment by craigsned** [comment]
Thanks Alfredo.

I'm busy this afternoon, but will try and find time to update the files and let you know how it looks.

Many thanks for your help!

**Comment by craigsned** [comment]
Hi Alfredo,

Updated functions.php and it seems to be working fine now.
:-)

Thanks again!
Best regards,
Craig

**Comment by IZ7BOJ** [comment]
Great!
Thank you for your help and tests!

73’s
Alfredo

Il giorno ven 7 gen 2022 alle 15:43 craigsned ***@***.***> ha
scritto:

**Comment by IZ7BOJ** [comment]
If you fint it useful, you can update frames.php.
Now the DTI field is verbose and explains the symbol meaning

**Comment by IZ7BOJ** [comment]
Craig, I just updated functions.php and summary.php in order to show the
last position packet in case both packets with and without position are
received.
I hope this helps,
73'
Alfredo

Il giorno ven 7 gen 2022 alle ore 19:37 Alfredo Vania ***@***.***> ha
scritto:

**Comment by craigsned** [comment]
Thanks again Alfredo.  I'll update the files over the weekend and let you know how it looks.73CraigOn 7 Jan 2022 21:55, Alfredo Vania - IZ7BOJ ***@***.***> wrote:

Craig, I just updated functions.php and summary.php in order to show the

last position packet in case both packets with and without position are

received.

I hope this helps,

73'

Alfredo



Il giorno ven 7 gen 2022 alle ore 19:37 Alfredo Vania ***@***.***> ha

scritto:

**Comment by craigsned** [comment]
Hi Alfredo,

 

I have updated both files and it’s looking good!

Thanks again!

73

Craig
