### ISSUE TITLE
No content on Summary.php

### ISSUE THREAD

**Issue by craigsned** [IZ7BOJ/direwolf_webstat#3]
Hi Alfredo,

I just installed on a new machine.  Logs are running fine, but nothing is showing up on the summary.php page.   Live.php is reporting as expected.

I've tried all of the timescale options - 1 hour to All, but nothing is showing.  summary tells me that there are 3 stations and 39 frames in the log....

Show frames of a specified station (frames.php) is also working ok, it is just the summary page that is not.

Craig

**Comment by craigsned** [comment]
I would add that the version I have which is working is the original one you helped me with some months ago (no Miles option on distance).  The version that I have just loaded I downloaded from Git today (has a miles option on distance)

Craig

**Comment by IZ7BOJ** [comment]
Hi,
I’ll have a look into the code tomorrow.
Could you tell me if you find errors in your http server log? If you use
lighttpd, you should find in /var/log/lighttpd/error.log or something
similar.
Thanks
Alfredo

Il giorno mer 11 mag 2022 alle 19:13 craigsned ***@***.***>
ha scritto:

**Comment by craigsned** [comment]
Ah yes, there are a few... 
[error.log](https://github.com/IZ7BOJ/direwolf_webstat/files/8672262/error.log)
 Looks like an issue with the PHP install?  I'm using PHP8.0 on Bullseye

**Comment by craigsned** [comment]
Hi Alfredo,

I've checked PHP install as far as I can.  Attached the output from phpinfo.php

Thanks
[PHP 8.0.1 - phpinfo().pdf](https://github.com/IZ7BOJ/direwolf_webstat/files/8672838/PHP.8.0.1.-.phpinfo.pdf)

Craig

**Comment by craigsned** [comment]
Hi Alfredo,
I managed to resolve - discovered that the each function is deprecated from PHP 7.2 and totally removed from 8.0.  I've reverted back to PHP7.4 and the summary.php is now working.

**Comment by IZ7BOJ** [comment]
Hi Craig,
yes, from the log was evident that the problem was each().
I should update the code and find an alternative solution for replacing that function.
I'll try as soon as I can.
For now, thank you very much for you help!
73's
Alfredo

**Comment by IZ7BOJ** [comment]
@craigsned I replaced the "each" function with "foreach" , which should be compatible with php8.
Do you still have php 8 installed in order to try the modification?
I don't have php 8 richt now..
Pleas let me know
73's
Alfredo
